name: PowerUpStack Upload

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set +e
          python -m pip install --upgrade pip
          pip install selenium pillow

      - name: Install ChromeDriver
        run: |
          set +e
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "✅ ChromeDriver installed."

      - name: Run upload script
        env:
          PUP_USER: ${{ secrets.PUP_USER }}
          PUP_PASS: ${{ secrets.PUP_PASS }}
        run: |
          set +e
          python3 scripts/powerup_upload.py || echo "⚠️ Script continued despite error"

      - name: Commit screenshots
        run: |
          set +e
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add screenshots/*.png || true
          git commit -m "Update Selenium screenshots" || echo "No changes"
          git push || echo "Nothing to push"
