name: Fetch and Darken Armor Textures

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  process_armor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Download armor textures from Mojang samples
        run: |
          mkdir -p Pack/textures/models/armor
          cd Pack/textures/models/armor

          BASE_URL="https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/models/armor"
          FILES=("chain_1.png" "chain_2.png" "iron_1.png" "iron_2.png" "diamond_1.png" "diamond_2.png" "leather_1.png" "leather_2.png" "gold_2.png" "gold_1.png" "netherite_1.png" "netherite_2.png")

          for f in "${FILES[@]}"; do
            curl -L -O "$BASE_URL/$f"
          done

      - name: Darken armor textures
        run: |
          cd Pack/textures/models/armor
          for img in *.png; do
            convert "$img" -modulate 80,100,100 "$img"
          done

      - name: Commit and push updated textures
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add Pack/textures/models/armor/*.png
          git commit -m "Auto-update: darkened armor textures from Mojang samples"
          git push
