name: Download and Convert to MCPACK

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download from MediaFire
        run: |
          URL="https://www.mediafire.com/file/a77tav57wf1x8si/%25C2%25A7bNebula_%25C2%25A78%255B%25C2%25A7f16%25C2%25A7bx%25C2%25A78%255D.zip/file"
          # 実体URL抽出
          DL_URL=$(curl -Ls "$URL" | grep -o 'https://download[^"]*')
          curl -L "$DL_URL" -o nebula.zip

      - name: Convert ZIP to MCPACK
        run: |
          mv nebula.zip nebula.mcpack

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mkdir -p output
          mv nebula.mcpack output/
          git add output/nebula.mcpack
          git commit -m "Update mcpack automatically"
          git push
